services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://server:3001/api
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CLIENT_URL=http://client:4000
      - PORT=3001
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_ADMIN=${SMTP_ADMIN}
    restart: unless-stopped
